# Generated by Django 4.2.1 on 2023-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_list_date_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_opened',
            field=models.DateTimeField(),
        ),
    ]
