# Generated by Django 4.2.1 on 2023-05-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_remove_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_opened',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
